### ISSUE TITLE
Chapter 12

### ISSUE THREAD

**Issue by signmeupo** [Jumaruba/LPL-solutions#39]
Is there a reason you didn't posted chapter 12 at all? I could really use some help with that rn

**Comment by WoongheeLee** [comment]
You might find from https://github.com/WoongheeLee/LPL-solutions/tree/master/Chapter%2012

**Comment by Jumaruba** [comment]
Merged some chapters from [this](https://github.com/Jumaruba/LPL-solutions/pull/38) PR. 
Closing this issue.
